packages: []
catalogs:
  build:
    unbuild: ^3.6.1
  cli:
    bumpp: ^10.2.3
    pncat: ^0.5.0
    taze: ^19.3.0
  dev:
    typescript: ^5.9.2
  lint:
    '@antfu/eslint-config': ^5.2.1
    eslint: ^9.34.0
    lint-staged: ^16.1.5
    simple-git-hooks: ^2.13.1
  node:
    ansis: ^4.1.0
    cac: ^6.7.14
    pathe: ^2.0.3
    yocto-spinner: ^1.0.0
  prod:
    yaml: ^2.8.1
  script:
    tsx: ^4.20.5
  test:
    vitest: ^3.2.4
  types:
    '@types/node': ^24.3.0
  utils:
    colord: ^2.9.3
